;
; File generated by cc65 v 2.16 - Git 83890e5
;
	.fopt		compiler,"cc65 v 2.16 - Git 83890e5"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "lesson24.c", 2943, 1520805812
	.dbg		file, "neslib.h", 8578, 1492006296
	.dbg		file, "lesson24.h", 1562, 1520800394
	.dbg		file, "Sprites.c", 2254, 1520805763
	.forceimport	__STARTUP__
	.dbg		sym, "pal_bg", "00", extern, "_pal_bg"
	.dbg		sym, "pal_spr", "00", extern, "_pal_spr"
	.dbg		sym, "ppu_wait_nmi", "00", extern, "_ppu_wait_nmi"
	.dbg		sym, "ppu_on_all", "00", extern, "_ppu_on_all"
	.dbg		sym, "oam_clear", "00", extern, "_oam_clear"
	.dbg		sym, "oam_spr", "00", extern, "_oam_spr"
	.dbg		sym, "oam_meta_spr", "00", extern, "_oam_meta_spr"
	.dbg		sym, "pad_poll", "00", extern, "_pad_poll"
	.dbg		sym, "bank_spr", "00", extern, "_bank_spr"
	.dbg		sym, "vram_adr", "00", extern, "_vram_adr"
	.dbg		sym, "vram_write", "00", extern, "_vram_write"
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_spr
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_write
	.export		_PAD_STATE
	.export		_PAD_STATE2
	.export		_PAD_STATET
	.export		_PAD_STATET2
	.export		_Y_position
	.export		_X_position
	.export		_X_position2
	.export		_X_position3
	.export		_sprid
	.export		_sprite_index
	.export		_metasprite_0_data
	.export		_metasprite_1_data
	.export		_metasprite_2_data
	.export		_metasprite_3_data
	.export		_metasprite_4_data
	.export		_metasprite_5_data
	.export		_metasprite_6_data
	.export		_metasprite_7_data
	.export		_metasprite_8_data
	.export		_metasprite_9_data
	.export		_metasprite_10_data
	.export		_metasprite_11_data
	.export		_metasprite_12_data
	.export		_metasprite_13_data
	.export		_metasprite_14_data
	.export		_metasprite_15_data
	.export		_metasprite_list1
	.export		_metasprite_list2
	.export		_Test
	.export		_PaletteBackgroud
	.export		_PaletteSprites
	.export		_metasprite
	.export		_metasprite_list
	.export		_main

.segment	"DATA"

_metasprite:
	.word	$0000
_metasprite_list:
	.word	$0000

.segment	"RODATA"

_metasprite_0_data:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$10
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$11
	.byte	$00
	.byte	$80
_metasprite_1_data:
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$13
	.byte	$00
	.byte	$80
_metasprite_2_data:
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$14
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$15
	.byte	$00
	.byte	$80
_metasprite_3_data:
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$16
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$17
	.byte	$00
	.byte	$80
_metasprite_4_data:
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$18
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$19
	.byte	$00
	.byte	$80
_metasprite_5_data:
	.byte	$00
	.byte	$08
	.byte	$1A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0B
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1B
	.byte	$00
	.byte	$80
_metasprite_6_data:
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1D
	.byte	$00
	.byte	$80
_metasprite_7_data:
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$1E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$1F
	.byte	$00
	.byte	$80
_metasprite_8_data:
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$30
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$31
	.byte	$00
	.byte	$80
_metasprite_9_data:
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$32
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$33
	.byte	$00
	.byte	$80
_metasprite_10_data:
	.byte	$00
	.byte	$00
	.byte	$24
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$25
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$34
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$35
	.byte	$00
	.byte	$80
_metasprite_11_data:
	.byte	$00
	.byte	$00
	.byte	$26
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$27
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$36
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$37
	.byte	$00
	.byte	$80
_metasprite_12_data:
	.byte	$00
	.byte	$00
	.byte	$28
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$29
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$38
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$39
	.byte	$00
	.byte	$80
_metasprite_13_data:
	.byte	$00
	.byte	$00
	.byte	$2A
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$3A
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$3B
	.byte	$00
	.byte	$80
_metasprite_14_data:
	.byte	$00
	.byte	$00
	.byte	$2C
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$3C
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$3D
	.byte	$00
	.byte	$80
_metasprite_15_data:
	.byte	$00
	.byte	$00
	.byte	$2E
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$2F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$3E
	.byte	$00
	.byte	$08
	.byte	$08
	.byte	$3F
	.byte	$00
	.byte	$80
_metasprite_list1:
	.addr	_metasprite_8_data
	.addr	_metasprite_9_data
	.addr	_metasprite_10_data
	.addr	_metasprite_11_data
	.addr	_metasprite_12_data
	.addr	_metasprite_13_data
	.addr	_metasprite_14_data
	.addr	_metasprite_15_data
	.word	$0000
_metasprite_list2:
	.addr	_metasprite_0_data
	.addr	_metasprite_1_data
	.addr	_metasprite_2_data
	.addr	_metasprite_3_data
	.addr	_metasprite_4_data
	.addr	_metasprite_5_data
	.addr	_metasprite_6_data
	.addr	_metasprite_7_data
	.word	$0000
_Test:
	.byte	$53,$70,$72,$69,$74,$65,$73,$00
_PaletteBackgroud:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_PaletteSprites:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"BSS"

.segment	"ZEROPAGE"
_PAD_STATE:
	.res	1,$00
_PAD_STATE2:
	.res	1,$00
_PAD_STATET:
	.res	1,$00
_PAD_STATET2:
	.res	1,$00
.segment	"BSS"
_Y_position:
	.res	1,$00
_X_position:
	.res	1,$00
_X_position2:
	.res	1,$00
_X_position3:
	.res	1,$00
_sprid:
	.res	1,$00
_sprite_index:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"

.segment	"CODE"

;
; pal_bg(PaletteBackgroud);
;
	.dbg	line, "lesson24.c", 44
	lda     #<(_PaletteBackgroud)
	ldx     #>(_PaletteBackgroud)
	jsr     _pal_bg
;
; pal_spr(PaletteSprites);
;
	.dbg	line, "lesson24.c", 45
	lda     #<(_PaletteSprites)
	ldx     #>(_PaletteSprites)
	jsr     _pal_spr
;
; bank_spr(1);
;
	.dbg	line, "lesson24.c", 49
	lda     #$01
	jsr     _bank_spr
;
; vram_adr(NTADR_A(7, 14)); // screen is 32 x 30 tiles
;
	.dbg	line, "lesson24.c", 54
	ldx     #$21
	lda     #$C7
	jsr     _vram_adr
;
; vram_write((unsigned char*)Test, sizeof(Test));
;
	.dbg	line, "lesson24.c", 57
	lda     #<(_Test)
	ldx     #>(_Test)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _vram_write
;
; ppu_on_all();
;
	.dbg	line, "lesson24.c", 66
	jsr     _ppu_on_all
;
; Y_position = 0x80;
;
	.dbg	line, "lesson24.c", 69
	lda     #$80
	sta     _Y_position
;
; X_position = 0x88;
;
	.dbg	line, "lesson24.c", 70
	lda     #$88
	sta     _X_position
;
; X_position2 = 0xa0;
;
	.dbg	line, "lesson24.c", 71
	lda     #$A0
	sta     _X_position2
;
; X_position3 = 0xc0;
;
	.dbg	line, "lesson24.c", 72
	lda     #$C0
	sta     _X_position3
;
; sprite_index = 0;
;
	.dbg	line, "lesson24.c", 74
	lda     #$00
	sta     _sprite_index
;
; metasprite_list = metasprite_list1;
;
	.dbg	line, "lesson24.c", 75
	lda     #<(_metasprite_list1)
	sta     _metasprite_list
	lda     #>(_metasprite_list1)
	sta     _metasprite_list+1
;
; ppu_wait_nmi();
;
	.dbg	line, "lesson24.c", 81
L0167:	jsr     _ppu_wait_nmi
;
; pad_poll(0); // read controller 1
;
	.dbg	line, "lesson24.c", 83
	lda     #$00
	jsr     _pad_poll
;
; pad_poll(1); // read controller 2
;
	.dbg	line, "lesson24.c", 84
	lda     #$01
	jsr     _pad_poll
;
; oam_clear();
;
	.dbg	line, "lesson24.c", 87
	jsr     _oam_clear
;
; sprid = 0;
;
	.dbg	line, "lesson24.c", 90
	lda     #$00
	sta     _sprid
;
; sprid = oam_spr(X_position, Y_position, 0, 0, sprid);
;
	.dbg	line, "lesson24.c", 95
	jsr     decsp4
	lda     _X_position
	ldy     #$03
	sta     (sp),y
	lda     _Y_position
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	dey
	sta     (sp),y
	lda     _sprid
	jsr     _oam_spr
	sta     _sprid
;
; sprite_index++;
;
	.dbg	line, "lesson24.c", 97
	inc     _sprite_index
;
; metasprite = metasprite_list[sprite_index >> ANIMATION_SHIFT];
;
	.dbg	line, "lesson24.c", 98
	ldx     #$00
	lda     _sprite_index
	lsr     a
	lsr     a
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     _metasprite_list
	sta     ptr1
	lda     tmp1
	adc     _metasprite_list+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     _metasprite
	stx     _metasprite+1
;
; if (metasprite == 0)
;
	.dbg	line, "lesson24.c", 99
	cpx     #$00
	bne     L017E
	cmp     #$00
	bne     L017E
;
; sprite_index = 0;
;
	.dbg	line, "lesson24.c", 101
	sta     _sprite_index
;
; metasprite = metasprite_list[0];
;
	.dbg	line, "lesson24.c", 102
	lda     _metasprite_list
	sta     ptr1
	lda     _metasprite_list+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	sta     _metasprite+1
	lda     (ptr1,x)
	sta     _metasprite
;
; sprid = oam_meta_spr(X_position2, Y_position, sprid, metasprite);
;
	.dbg	line, "lesson24.c", 107
L017E:	jsr     decsp3
	lda     _X_position2
	ldy     #$02
	sta     (sp),y
	lda     _Y_position
	dey
	sta     (sp),y
	lda     _sprid
	dey
	sta     (sp),y
	lda     _metasprite
	ldx     _metasprite+1
	jsr     _oam_meta_spr
	sta     _sprid
;
; if ((PAD_STATET & PAD_UP) != 0)
;
	.dbg	line, "lesson24.c", 112
	lda     _PAD_STATET
	and     #$10
	beq     L019D
;
; metasprite_list = metasprite_list1;
;
	.dbg	line, "lesson24.c", 114
	lda     #<(_metasprite_list1)
	sta     _metasprite_list
	lda     #>(_metasprite_list1)
	sta     _metasprite_list+1
;
; sprite_index = 0;
;
	.dbg	line, "lesson24.c", 115
	lda     #$00
	sta     _sprite_index
;
; else if ((PAD_STATET & PAD_DOWN) != 0)
;
	.dbg	line, "lesson24.c", 117
	jmp     L0167
L019D:	lda     _PAD_STATET
	and     #$20
	jeq     L0167
;
; metasprite_list = metasprite_list2;
;
	.dbg	line, "lesson24.c", 119
	lda     #<(_metasprite_list2)
	sta     _metasprite_list
	lda     #>(_metasprite_list2)
	sta     _metasprite_list+1
;
; sprite_index = 0;
;
	.dbg	line, "lesson24.c", 120
	lda     #$00
	sta     _sprite_index
;
; while (1)
;
	.dbg	line, "lesson24.c", 78
	jmp     L0167
	.dbg	line

.endproc

